---
namespace: "victoriametrics"
name: "cluster"
version: "0.0.0"
readme: "README.md"
authors:
    - "Zakhar Bessarab <z.bessarab@victoriametrics.com>"
license:
    - "Apache-2.0"
tags:
    - victoriametrics
    - monitoring
repository: "https://github.com/VictoriaMetrics/ansible-playbooks"
build_ignore:
    - .git
    - .github
    - build
    - inventory_example
    - Vagrantfile
    - '*.tar.gz'
    - Makefile
    - requirements.txt
homepage: "https://github.com/VictoriaMetrics/ansible-playbooks"
documentation: "https://github.com/VictoriaMetrics/ansible-playbooks"
issues: "https://github.com/VictoriaMetrics/ansible-playbooks/issues"
