- name: Ensure license key is provided
  ansible.builtin.assert:
    that: vic_vm_alert_license_key != "" or vic_vm_alert_license_key_file != ""
    msg: Either license key or license key file location must be provided.
  when: vic_vm_alert_enterprise | bool

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vic_vm_alert_license_key_file == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vic_vm_alert_enterprise | bool
    - vic_vm_alert_license_key != ""

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vic_vm_alert_license_key == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vic_vm_alert_enterprise | bool
    - vic_vm_alert_license_key_file != ""

- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vic_vm_alert_service_args: "{{ vic_vm_alert_service_args | combine({'license': vic_vm_alert_license_key}) }}"
  when:
    - vic_vm_alert_enterprise | bool
    - vic_vm_alert_license_key != ""


- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vic_vm_alert_service_args: "{{ vic_vm_alert_service_args | combine({'licenseFile': vic_vm_alert_license_key_file}) }}"
  when:
    - vic_vm_alert_enterprise | bool
    - vic_vm_alert_license_key_file != ""
