---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include vmstorage"
      vars:
        vmstorage_enterprise: true
        vmstorage_license_key_file: "/tmp/vm-license"
      ansible.builtin.include_role:
        name: "vmstorage"
