- name: Ensure license key is provided
  ansible.builtin.assert:
    that: vmstorage_license_key != "" or vmstorage_license_key_file != ""
    msg: Either license key or license key file location must be provided.
  when: vmstorage_enterprise | bool

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vmstorage_license_key_file == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key != ""

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vmstorage_license_key == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key_file != ""

- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vmstorage_config: "{{ vmstorage_config | combine({'license': vmstorage_license_key}) }}"
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key != ""

- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vmstorage_config: "{{ vmstorage_config | combine({'licenseFile': vmstorage_license_key_file}) }}"
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key_file != ""
