- name: Ensure license key is provided
  ansible.builtin.assert:
    that: vmauth_license_key != "" or vmauth_license_key_file != ""
    msg: Either license key or license key file location must be provided.
  when: vmauth_enterprise | bool

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vmauth_license_key_file == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vmauth_enterprise | bool
    - vmauth_license_key != ""

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vmauth_license_key == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vmauth_enterprise | bool
    - vmauth_license_key_file != ""


- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vmauth_service_args: "{{ vmauth_service_args | combine({'license': vmauth_license_key}) }}"
  when:
    - vmauth_enterprise | bool
    - vmauth_license_key != ""


- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vmauth_service_args: "{{ vmauth_service_args | combine({'licenseFile': vmauth_license_key_file}) }}"
  when:
    - vmauth_enterprise | bool
    - vmauth_license_key_file != ""
