---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include vmselect"
      vars:
        vmselect_enterprise: true
        vmselect_license_key_file: "/tmp/vm-license"
      ansible.builtin.include_role:
        name: "vmselect"
