---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include vmauth"
      vars:
        vmauth_enterprise: true
        vmauth_license_key_file: "/tmp/vm-license"
      ansible.builtin.include_role:
        name: "vmauth"
